apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::075117883788:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
    - groups:   
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::075117883788:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19GFJOB73BOMD
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-26T03:15:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "892"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2d068a37-81c4-4f25-a765-3c06022b33c2
